<a href="https://colab.research.google.com/github/Gus-1003/ISD-invention/blob/main/Plots/2D_Heatmap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/drive/')

%cd /content/drive/MyDrive/

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
/content/drive/MyDrive


In [2]:
import plotly.express as px
import pandas as pd # manipulação e análise de dados
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
df = pd.read_csv('/content/drive/Shareddrives/Videos OPTO/Videos_DLC/MTOP10-TEST-E1DLC_resnet50_Videos OPTOSep1shuffle1_182500.csv')
df.head()

scorer DLC_resnet50_Videos OPTOSep1shuffle1_182500  \
0  bodyparts                                        nose   
1     coords                                           x   
2          0                          310.13983154296875   
3          1                           309.8239440917969   
4          2                           308.1839599609375   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.1  \
0                                          nose   
1                                             y   
2                              102.134033203125   
3                            101.36891174316406   
4                             99.10370635986328   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.2  \
0                                          nose   
1                                    likelihood   
2                            0.9999874830245972   
3                            0.9999675750732422   
4                            0.9999431371688843   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.3  \
0                                         ear_l   
1                                             x   
2                             281.1981201171875   
3                            281.12725830078125   
4                            280.69439697265625   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.4  \
0                                         ear_l   
1                                             y   
2                             92.22260284423828   
3                             91.93657684326172   
4                             91.14391326904297   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.5  \
0                                         ear_l   
1                                    likelihood   
2                            0.9999496936798096   
3                            0.9999152421951294   
4                            0.9998340606689453   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.6  \
0                                         ear_r   
1                                             x   
2                            283.69073486328125   
3                             283.7317810058594   
4                            283.73284912109375   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.7  \
0                                         ear_r   
1                                             y   
2                            115.04375457763672   
3                             114.7477798461914   
4                            113.38082885742188   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.8  \
0                                         ear_r   
1                                    likelihood   
2                             0.999889612197876   
3                            0.9998282194137573   
4                            0.9997654557228088   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.9  \
0                                        center   
1                                             x   
2                            224.72584533691406   
3                            224.72340393066406   
4                            224.67320251464844   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.10  \
0                                         center   
1                                              y   
2                             103.58444213867188   
3                              103.5401611328125   
4                             103.69190979003906   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.11  \
0                                         center   
1                                     likelihood   
2                             0.9998608827590942   
3                             0.9998639822006226   
4                             0.9998692274093628   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.12  \
0                                      tail_base   
1                                              x   
2                             204.18807983398438   
3                              203.9853057861328

In [4]:
# Para excluir as três primeiras colunas (A, B e C)
df = df.iloc[:, 1:]

# Agora 'df' conterá apenas as colunas D em diante
df.head()

DLC_resnet50_Videos OPTOSep1shuffle1_182500  \
0                                        nose   
1                                           x   
2                          310.13983154296875   
3                           309.8239440917969   
4                           308.1839599609375   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.1  \
0                                          nose   
1                                             y   
2                              102.134033203125   
3                            101.36891174316406   
4                             99.10370635986328   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.2  \
0                                          nose   
1                                    likelihood   
2                            0.9999874830245972   
3                            0.9999675750732422   
4                            0.9999431371688843   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.3  \
0                                         ear_l   
1                                             x   
2                             281.1981201171875   
3                            281.12725830078125   
4                            280.69439697265625   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.4  \
0                                         ear_l   
1                                             y   
2                             92.22260284423828   
3                             91.93657684326172   
4                             91.14391326904297   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.5  \
0                                         ear_l   
1                                    likelihood   
2                            0.9999496936798096   
3                            0.9999152421951294   
4                            0.9998340606689453   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.6  \
0                                         ear_r   
1                                             x   
2                            283.69073486328125   
3                             283.7317810058594   
4                            283.73284912109375   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.7  \
0                                         ear_r   
1                                             y   
2                            115.04375457763672   
3                             114.7477798461914   
4                            113.38082885742188   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.8  \
0                                         ear_r   
1                                    likelihood   
2                             0.999889612197876   
3                            0.9998282194137573   
4                            0.9997654557228088   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.9  \
0                                        center   
1                                             x   
2                            224.72584533691406   
3                            224.72340393066406   
4                            224.67320251464844   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.10  \
0                                         center   
1                                              y   
2                             103.58444213867188   
3                              103.5401611328125   
4                             103.69190979003906   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.11  \
0                                         center   
1                                     likelihood   
2                             0.9998608827590942   
3                             0.9998639822006226   
4                             0.9998692274093628   

  DLC_resnet50_Videos OPTOSep1shuffle1_182500.12  \
0                                      tail_base   
1                                              x   
2                             204.18807983398438   
3                              203.9853057861328   
4                             203.62205505371094   

  DLC

In [5]:
# Concatene as linhas 0 e 1
concatenated_row = df.iloc[0] + "_" + df.iloc[1]
df.iloc[0] = concatenated_row

# Substituir os nomes das colunas pelo conteúdo da primeira linha
df.columns = df.iloc[0]

# Remover a primeira linha (índice 0)
df = df[2:]

# Reset o índice
df.reset_index(drop=True, inplace=True)

# Agora 'df' conterá apenas as colunas D em diante
df.head()

<ipython-input-5-4ff4d02a575a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[0] = concatenated_row


0              nose_x              nose_y     nose_likelihood  \
0  310.13983154296875    102.134033203125  0.9999874830245972   
1   309.8239440917969  101.36891174316406  0.9999675750732422   
2   308.1839599609375   99.10370635986328  0.9999431371688843   
3   307.7093200683594   96.17938232421875  0.9998074173927307   
4   303.8755187988281    95.0369644165039     0.9993896484375   

0             ear_l_x            ear_l_y    ear_l_likelihood  \
0   281.1981201171875  92.22260284423828  0.9999496936798096   
1  281.12725830078125  91.93657684326172  0.9999152421951294   
2  280.69439697265625  91.14391326904297  0.9998340606689453   
3  279.88873291015625  89.20172882080078  0.9998644590377808   
4   278.8699035644531  87.65206909179688  0.9999176263809204   

0             ear_r_x             ear_r_y    ear_r_likelihood  \
0  283.69073486328125  115.04375457763672   0.999889612197876   
1   283.7317810058594   114.7477798461914  0.9998282194137573   
2  283.73284912109375  113.38082885742188  0.9997654557228088   
3   286.1210632324219  112.83187866210938  0.9993988275527954   
4  285.34356689453125  110.68675231933594  0.9991416931152344   

0            center_x            center_y   center_likelihood  \
0  224.72584533691406  103.58444213867188  0.9998608827590942   
1  224.72340393066406   103.5401611328125  0.9998639822006226   
2  224.67320251464844  103.69190979003906  0.9998692274093628   
3  224.40362548828125  103.65623474121094  0.9998370409011841   
4   223.8165283203125  103.66327667236328  0.9998339414596558   

0         tail_base_x         tail_base_y tail_base_likelihood  
0  204.18807983398438   124.4105224609375   0.9115631580352783  
1   203.9853057861328  124.42320251464844   0.9048246145248413  
2  203.62205505371094  124.35816192626953    0.918399453163147  
3   203.7176055908203  124.47272491455078    0.886262059211731  
4  203.82699584960938   124.7862777709961   0.8772501349449158

In [24]:
y_max

429

In [29]:
# Converta as colunas center_x e center_y para valores numéricos
df['center_x'] = pd.to_numeric(df['center_x'])
df['center_y'] = pd.to_numeric(df['center_y'])

# Defina o tamanho da grade arredondando para o inteiro mais próximo
x_max, y_max = int(round(df['center_x'].max())), int(round(df['center_y'].max()))

# Crie uma matriz de zeros de ponto flutuante do tamanho da grade
z = np.zeros((y_max, x_max), dtype=np.float32)

# Preencha a matriz com base nas coordenadas center_x e center_y
for _, row in df.iterrows():
    x, y = int(row['center_x']), int(row['center_y'])
    if 0 < x < x_max and 0 < y < y_max:
        z[y, x] += 1.0  # Aumenta a contagem na posição (x, y) como ponto flutuante
        print(x, y, z)

# Crie um gráfico de calor 2D
sns.heatmap(data=z, cmap='YlGnBu', vmin=0, vmax=z.max())

# Configure os rótulos dos eixos
plt.xlabel('x')
plt.ylabel('y')

# Exiba o gráfico
plt.show()

A saída de streaming foi truncada nas últimas 5000 linhas.
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
214 175 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
214 175 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
213 175 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
213 174 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
212 174 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
212 175 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. .

KeyboardInterrupt: ignored

In [19]:
z[225, 104]

0.0